name: Web Tests

on:
  pull_request:
    paths:
      - 'web/**/*'
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    
    strategy:
      matrix:
        node-version: ["20"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint
  
    - name: Run type checking
      run: npx tsc --noEmit
      
    - name: Run tests
      run: npm run test:run

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true